### ISSUE TITLE
'list index out of range' Error in Data Analysis Module.

### ISSUE THREAD

**Issue by smyconan** [behzadk/AutoCD#4]
I've done the process of model space generation & model selection. But errors appear in data analysis which are as the following:
```
Traceback (most recent call last):
  File "run_AutoCD.py", line 82, in <module>
    main()
  File "run_AutoCD.py", line 78, in main
    run_data_analysis.main(data_analysis_config)
  File "/home/AutoCD/data_analysis/run_data_analysis.py", line 35, in main
    model_space_report_df = ABC_DA.write_combined_model_space_report(finished_exp_final_population_dirs, combined_analysis_output_dir) 
  File "/home/AutoCD/data_analysis/data_analysis_ABCSMC.py", line 855, in write_combined_model_space_report
    model_space_report_df = merge_model_space_report_df_list(model_space_report_list)
  File "/home/AutoCD/data_analysis/data_analysis_ABCSMC.py", line 46, in merge_model_space_report_df_list
    model_space_report_df = df_list[0]
IndexError: list index out of range
```

I think that it's because the df_list is empty, but why it happens when I've already done the model space generation & model selection? By the way, I'm just following your example bash script at the bottom of your README.

I'm not familiar with the microbial community design, so maybe the problem is minor for yours. But I'm still looking forward to your reply, thank you!

**Comment by behzadk** [comment]
Hi,
It's looking for the output data from ABC SMC. Can you see these outputs in the different experiment folders?

Perhaps you need to change the DA_config yaml file so it's pointing to the correct output folder?

**Comment by smyconan** [comment]
> Hi,
> It's looking for the output data from ABC SMC. Can you see these outputs in the different experiment folders?
> 
> Perhaps you need to change the DA_config yaml file so it's pointing to the correct output folder?

The yaml files of configuration is like the following:

MSG two strain:
```
# Set absolute paths to output of ModelSpageGenerator (MSG) 
model_space_name: input_files_two_strain_0

# Output model space to the ABC input files dir
output_dir: "./ABC_input_files/"

# Paths referring to .csv files containing 
# default parameter and initial species prior ranges
default_parameters_path: './ModelSpaceGenerator/default_params/default/default_params.csv'
default_initial_species_path: './ModelSpaceGenerator/default_params/default/default_init_species.csv'
```
ABC two strain:
```
experiment_name: two_strain_0_SMC
population_modules_path: './ABC_input_files/input_files_two_strain_0/population_modules.so'
inputs_folder: './ABC_input_files/input_files_two_strain_0/input_files/'
output_folder: './output/'
```
DA two strain
```
experiment_name: two_strain_0_SMC
inputs_folder: './ABC_input_files/input_files_two_strain_0/'
output_folder: './output/'
```

And initially, the `ABC_input_files` and `output` folders are empty.
After the MSG process (it says `No ABC config, skipping ABC...`, but I think it's not a case since ABC process doesn't run yet.), the `ABC_input_files` folder is like the following:
```
.
`-- input_files_two_strain_0
    |-- adj_matricies
    |-- input_files
    |-- model.cpp
    |-- model.h
    |-- population_modules.so
    `-- py_eqs_txt_files
```
Then after the ABC selection process (it still says `No ABC config, skipping ABC... `, I'm not sure if it is OK.), the `output` folder is like the following:
```
.
|-- two_strain_0_SMC
|-- two_strain_0_SMC_0
|   |-- ABC_two_strain.yaml
|   |-- Population_0
|   |-- Population_1
|   `-- Population_2
`-- two_strain_0_SMC_0_pop_2.tar.gz
```
Then I run the DA process, it shows the error above. 

I'm not sure if the issue comes from the difference of experiment name `two_strain_0_SMC` and `two_strain_0_SMC_0`, or the `skipping ABC` message, or the DA config should include the path of `two_strain_0_SMC` instead of the ABC input path?

Thank you very much and waiting for your reply ^ ^

**Comment by behzadk** [comment]
Ok, I see the problem. The folder `two_strain_0_SMC_0` should be inside `two_strain_0_SMC`. I'll fix this later in the week. In the mean time, if you manually change the file structure you should be able to run the data analysis

**Comment by smyconan** [comment]
> Ok, I see the problem. The folder `two_strain_0_SMC_0` should be inside `two_strain_0_SMC`. I'll fix this later in the week. In the mean time, if you manually change the file structure you should be able to run the data analysis

Thank you behzadk! I've solve this problem by moving the folders, and can run the whole process for two strain.

But when I run the three strain process, I met `gcc-9: fatal error: Killed signal terminated program cc1plus` `compilation terminated.` error, which I think is because of the memory space? Is there any way to solve this issue? I've searched on google and found those solutions don't work. 

By the way, what scale of hardware resources did you use in this experiment? 

Best,

**Comment by behzadk** [comment]
What are you running when you encounter the memory error?

**Comment by smyconan** [comment]
> What are you running when you encounter the memory error?

I've already solved this issue ~ It's since that the three-strain task needs more memory resources to run. I've enlarged the memory size and it works now.

Thank you very much!
